settings:
  title: 'Status Page'
  url: 'https://status.zzu.pw' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded
  

monitors:
  - id: zerotrustengine-com
    name: 网站首页
    description: 'You write code. They handle the rest.'
    url: 'https://zerotrustengine.com/'
    method: GET
    expectStatus: 200 
    followRedirect: false 
    linkable: false
  - id: zzu-pw # unique identifier
    name: 短域名
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://zzu.pw/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: xzh-zzu-pw 
    name: 鑫账户演示
    description: 'You write code. They handle the rest.'
    url: 'https://xzh.zzu.pw/'
    method: GET
    expectStatus: 200 
    followRedirect: false 
    linkable: false
  - id: 32
    name: 国家地震科学数据中心
    description: ''
    url: 'https://data.earthquake.cn/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
  - id: 21
    name: 国家啮齿类实验动物资源库
    description: ''
    url: 'http://nrla.nifdc.org.cn'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
  - id: 23
    name: 国家海洋科学数据中心
    description: ''
    url: 'http://mds.nmdis.org.cn/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
